/// Bump when [entrypointSource] changes: it is part of the compile cache key.
const int entrypointTemplateVersion = 1;

/// The program the launcher compiles. Fixed text; the only variable input
/// is the user's `rask.dart` next to the workspace root's `pubspec.yaml`.
/// `RASK_CONFIG_KEY` is set by the launcher.
const String entrypointSource = '''
// Generated by rask. Do not edit; rask rewrites this file.
import 'dart:io';

import 'package:rask/rask.dart';
import '../../rask.dart' as user;

Future<void> main(List<String> args) async {
  exit(await runRask(args, user.config,
      configKey: Platform.environment['RASK_CONFIG_KEY'] ?? ''));
}
''';
